restore_cache: &restore_cache
  key: pip-{{ checksum "requirements/dev.txt" }}

install_dependencies: &install_dependencies
  name: Install Dependencies
  command: pip install -r requirements/dev.txt

save_cache: &save_cache
  key: pip-{{ checksum "requirements/dev.txt" }}
  paths:
    - "~/.cache/pip"
    - "~/.apt-cache"

python3_steps: &python3_steps
  steps:
    - checkout
    - restore_cache:
        <<: *restore_cache
    - run:
        <<: *install_dependencies
    - save_cache:
        <<: *save_cache
    - run:
        name: Run test
        command: make test

version: 2
jobs:
  python27:
    docker:
      - image: python:2.7.13
    working_directory: "~/custom_fields-py27/"
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache
      - run:
          <<: *install_dependencies
      - save_cache:
          <<: *save_cache
      - run:
          name: Run Tox
          command: tox -e py27
  python34:
    docker:
      - image: python:3.4
    working_directory: "~/custom_fields/"
    <<: *python3_steps
  python35:
    docker:
      - image: python:3.5
    working_directory: "~/custom_fields/"
    <<: *python3_steps
  python36:
    docker:
      - image: python:3.6
    working_directory: "~/custom_fields/"
    <<: *python3_steps


workflows:
  version: 2
  build_and_test:
    jobs:
      - python27
      - python34
      - python35
      - python36